### ISSUE TITLE
Disable music patch disables ice beam shooting sound as well

### ISSUE THREAD

**Issue by Miepee** [MetroidAdvRandomizerSystem/mars-patcher#75] opened 2024-09-05 20:08 UTC
Unsure if bug or feature...

**Comment by Miepee** [comment] 2024-09-05 21:04
On second thought, i think this was due to destroying an s1 stabilizer

**Comment by biosp4rk** [comment] 2024-09-09 01:11
I can't repro this. Can you see if there are steps that always cause this?

**Comment by biosp4rk** [comment] 2024-09-09 01:14
After looking at the other two issues, it must have happened after the last stabilizer was destroyed, since it plays a different sound

**Comment by biosp4rk** [comment] 2024-09-09 01:18
Duplicate of #76

**Closed by biosp4rk** 2024-09-09 01:18 UTC
